.circleci/config.yml, Dockerfile, bin/ashley, docker-compose.yml, env.d/development/postgresql, sandbox/settings.py, setup.cfg
Use PostgreSQL instead of SQLite in Development environment.
=> 🐳(project) use PostgreSQL instead of SQLite for development and tests

.circleci/config.yml, .dockerignore, .gitignore, Makefile, setup.cfg
Type hinting using the [PEP 484](https://www.python.org/dev/peps/pep-0484/) notation have been introduced in python 3.5. and I'm convinced that it's a good practice. 
Common bugs can be detected and avoided easily with static type checkers, and [mypy](http://mypy-lang.org/) is one of them.
=> ✨(project) add static type checking with mypy

Makefile
There is an error (related to an old removed commit) in the Makefile in the task lint-mypy.
=> 🐛(project) fix error in Makefile for lint-mypy task

CHANGELOG.md, sandbox/settings.py, src/lti_provider/views.py
Ashley is meant to run embedded in iframes on external websites.
With the current configuration, it is not possible because of the following reasons : 
- django's [clickjacking middleware](https://docs.djangoproject.com/en/2.2/ref/clickjacking/) is sending a [X-Frame-Options](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options) header which prevent the `sandbox` project from running inside an iframe on an external website. None of the `X-Frame-Options` directive is suitable if we want to serve ashley as a service for multiple websites at the same time.
- Django CSRF and SESSION cookies are sent with the `SameSite=Lax` flag. If ashley is running inside an iframe on an external website, the cookies sent by ashley are ignored by the user browser.
- Disable the …
=> 🔧(sandbox) update security settings in sandbox

Dockerfile, bin/_config.sh, bin/ashley, bin/manage, bin/pylint, bin/pytest, bin/superuser, env.d/development/common
Execution of django management commands in development environment require to execute multiple commands. And, as developers, by definition, we are lazy.
Add a `bin/manage` script allows to execute directly django management commands inside a docker container.
Usage example : `bin/manage createsuperuser`
=> ✨(project) add script to execute management commands

setup.cfg
A new [release](https://django-machina.readthedocs.io/en/stable/release_notes/v1.1.html) of django-machina is out, with django 3 support :tada: 
As mentionned in [this issue](https://github.com/ellmetha/django-machina/issues/189#issuecomment-598808312) it only works with django-haystack 3.0b1 which is a pre-release version.
=> ⬆️(dependencies) upgrade django-machina to support django 3.0

.circleci/config.yml, CHANGELOG.md, Makefile, env.d/development/common, sandbox/dev_tools/__init__.py, sandbox/dev_tools/apps.py, sandbox/dev_tools/forms.py, sandbox/dev_tools/templates/dev/consumer.html, sandbox/dev_tools/urls.py, sandbox/dev_tools/views.py, sandbox/settings.py, sandbox/urls.py, src/lti_provider/factories.py
Developers should have a simple way to test ashley without having to run an openedx instance.
Add a standalone LTI consumer to test ashley.
- `make bootstrap`
- `make run`
- go to http://localhost:8090/dev/consumer
For the moment it only displays a greeting message if you are authenticated.
But when `feature/ashley-auth-backend` and `feature/permission-management` will be merged, you'll be able to see the forum in action.
=> ✨(dev-tools) add a standalone LTI consumer to test ashley in development

CHANGELOG.md, src/ashley/permissions/__init__.py, src/ashley/permissions/groups.py, src/lti_provider/lti.py, tests/lti_provider/test_lti.py
Users having roles Administrator or Instructor should have extra permissions to moderate their forum.
=> ✨(ashley) add extra permission to course administrators

Dockerfile
The lti_provider module is missing in the production docker image.
=> 🐛(project) fix production docker image

setup.cfg
The factory-boy module is listed in the dev dependencies, but the sandbox needs it.
=> 🐛(sandbox) move factory_boy from dev to sandbox dependencies

setup.cfg
The gunicorn dependency is missing in the sandbox.
=> 🐛(sandbox) add missing dependency

sandbox/settings.py
A system check of the sandbox project is listing the following issues :
```
WARNINGS:
?: (security.W004) You have not set a value for the SECURE_HSTS_SECONDS setting. If your entire site is served only over SSL, you may want to consider setting a value and enabling HTTP Strict Transport Security. Be sure to read the documentation first; enabling HSTS carelessly can cause serious, irreversible problems.
?: (security.W008) Your SECURE_SSL_REDIRECT setting is not set to True. Unless your site should be available over both SSL and non-SSL connections, you may want to either set this setting True or configure a load balancer or reverse-proxy server to redirect all connections to HTTPS.
?: (security.W022) You have not set the SECURE_REFERRER_POLICY setting. Without this, your site will not send …
```
=> 🔧(sandbox) update settings to fix or silent security warnings

src/ashley/auth/backend.py, src/ashley/models.py, src/ashley/views.py, src/lti_provider/default/backend.py, src/lti_provider/validator.py
The logger names used in `ashley` and `lti_provider` are too generic.
Instead of using "ashley" and "lti_provider" as logger name, we now use full module name to be more precise.
=> 🔊(logging) update loggers to follow module name convention

CHANGELOG.md, setup.cfg, src/frontend/package.json
- lti_provider django application
- install `django-machina` forum in the `sandbox` project
- custom user model, auth backend and LTI handlers in `ashley`
- standalone LTI consumer to test ashley in development
- permission management and group synchronization based on LTI roles
- `asley.machina_extensions.forum` application to extend django-machina's forum model.
- automatic forum creation based on the context of the LTI launch request
- Instructor and Administrator LTI roles have special permissions on their forum.
- customize django-machina to have a basic set of forum features
- i18n support and translations with crowdin
- add basic CSS file in ashley to override machina's stylesheet
- each forum has its own unique LTI launch URL
- wysiwyg editor based on Draft.js
- Update sandbox …
=> 🔖(ashley) bump version to 1.0.0-beta.0

CHANGELOG.md, src/frontend/js/ashley.ts, src/frontend/js/utils/emojis.ts, src/frontend/package.json, src/frontend/scss/_main.scss, src/frontend/scss/objects/_emojis.scss, src/frontend/webpack.config.js, src/frontend/yarn.lock
Emojis are rendered with emojione in ashley WISYWIG editor. But when a
forum post is displayed, emojis are rendered with the native font of
the user's browser. In consequence, the rendering is inconsistent and
sometime emojis are not displayed at all.
Use emojione to render emojis everywhere.
=> ✨(ashley) render emojis with emojione

CHANGELOG.md, src/ashley/auth/backend.py, tests/ashley/test_auth_backend.py
I want to use Ashley as an external tool on Moodle, but I get a 403 with the following error : 
> Unable to find param lis_person_sourcedid in LTI request
The remote username (on the LTI consumer side) is sent to LTI Providers via various LTI parameters, depending on the LTI Consumer that initiates the launch request.
In OpenEdx, the parameter is `lis_person_sourcedid`.
In Moodle, the parameter is `ext_user_username`.
This PR adds support for `ext_user_username`.
As a result, we can use Ashley in Moodle :
=> ✨(ashley) add support for Moodle in ashley's LTI authentication backend

CHANGELOG.md, sandbox/settings.py, src/ashley/middleware.py, tests/ashley/test_middleware.py
Django < 3.1 does not allow to set the SameSite="None" attribute for the session and CSRF cookies. As a result, it causes issues with modern browsers that consider SameSite="Lax" by default.
=> 🐛(sandbox) add middleware to force SameSite=None on Django cookies

CHANGELOG.md, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/_main.scss
On firefox, the heading buttons (H1/H2/H3) are displayed on two lines.
=> 💄(ashley) fix heading button rendering in ashley editor on firefox

CHANGELOG.md, src/ashley/editor/decorators.py
Links posted in forum conversation are opened in the iframe displaying the forum. It's confusing for the forum users.
Also, if posted links are non secure (`http://`), a security error blocks the request when a user clicks on it :
> Mixed Content: The page at 'https://lti-consumer/' was loaded over HTTPS, but requested an insecure resource 'http://forum-post-link.example.com/'. This request has been blocked; the content must be served over HTTPS.
=> ✨(ashley) update draftjs link decorator

CHANGELOG.md, src/frontend/js/ashley.ts, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/_main.scss
We want to rewrite the ashleyeditor component in functional way using
hooks. To keep toolbar in top of the editor we use a css hack forcing
the top position on top on the editor.
=> ♻️(front) transform ashleyeditor component in functional component

CHANGELOG.md, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/_main.scss
To toggle focus on `AshleyEditor` component, a user can only click on the placeholder text.
Improve this behavior by extending the clickable area to the whole editor.
=> 🚸(front) improve focus management on ashleyeditor

.gitlint, gitlint/gitlint_emoji.py
Gitlint configuration is missing in the project.
As a result, PR generated by Renovate Bot can't be merged, since their body message can be empty depending on the context.
Add `.gitlint` file based on our other projects.
=> 🔧(project) add .gitlint configuration file

CHANGELOG.md, setup.cfg, src/frontend/package.json
- render emoji with emojione on forum posts
- add support for Moodle in ashley's LTI authentication backend
- add SameSiteNoneMiddleware to force SameSite=None on CSRF and session cookies
- update draftjs link decorator to open links in new tab and to add attribute
`rel="nofollow noopener noreferrer"`
- refactor `<AshleyEditor />` in functional component using hooks
- improve focus management on `<AshleyEditor />`
- heading buttons rendering in ashley editor on Firefox
=> 🔖(ashley) bump version to 1.0.0-beta.1

CHANGELOG.md, src/ashley/templates/board_base.html
When integrated in a small iframe, Ashley's layout is not using the full width available.
- [Bootstrap layout](https://getbootstrap.com/docs/4.0/layout/overview/)
- [Bootstrap spacing](https://getbootstrap.com/docs/4.0/utilities/spacing/)
=> 💄(template) use a fluid container for a better iframe integration

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- add dependency to bootstrap 4.4.1 and font-awesome 5.13.0
- add button to insert a link in AshleyEditor component
Changed
- build the forum CSS theme inside ashley instead of using the compiled CSS
file distributed with django-machina
- coalesce SASS color variables between django-machina and bootstrap
- use a fluid container for a better iframe integration
- change SASS colors
=> 🔖(ashley) bump version to 1.0.0-beta.2

Makefile
On the first bootstrap of the project with `make boostrap && make
run`, assets are missing and we need to run `make build-front`
manually.
=> 🐛(project) fix Makefile to build frontend assets in bootstrap target

CHANGELOG.md, sandbox/settings.py, src/ashley/validators.py, tests/ashley/test_validators.py
When a user try to set a signature containing rich text, a max length
validation error is raised. (See #85 )
This is due to the fact that the entire draft.js markup length is checked, not only the plain text.
Fixes #85.
=> 🐛(back) fix signature max length errors

CHANGELOG.md, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/objects/_editor.scss
We used a CSS hack to be able to place the Draft.js static toolbar
plugin above the editor, because it was not possible to place directly
the static-toolbar component above the editor.
This hack does not handle well the resizing of the editor, because of
the way it computes the height of the editor. It is one time behind
the reality.
Here is the result, as explained in #110 : 
Use absolute positionning for the toolbar instead of relative.
It avoids computing the height of the editor to position it.
=> 🐛(front) fix Draft.js editor resize issue with static toolbar

CHANGELOG.md, Dockerfile
The `upgrades` directory is missing from the production docker image
published on Docker Hub. As a consequence, it is not possible to run
the upgrade scripts when using it.
=> 🐛(package) add missing `upgrades` directory in distributed artifacts

setup.cfg
We don't want to upgrade the `elasticsearch` python package to a version
greater than 5, because Haystack doesn't support it.
=> 📌(pyup) add pyup filter to elasticsearch dependency

CHANGELOG.md, setup.cfg, src/frontend/package.json
- enable sentry_sdk in the sandbox
- allow users with empty username to define it
- email and public_username are now optional for LTI authentication
- detect and generate unique user id for OpenedX studio users
- `upgrades` directory is missing from the published docker image
=> 🔖(ashley) bump version to 1.0.0-beta.4

CHANGELOG.md, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/_main.scss, src/frontend/scss/_mixin.scss, src/frontend/scss/objects/_conversation_topic_detail.scss, src/frontend/scss/objects/_editor.scss
The input field to add a message is based on the draftjs editor and draftjs plugins. We want to be able to add a quote via this editor.
Based on issue https://github.com/openfun/ashley/issues/67
Add a "quote" button to the editor's toolbar that allows formatting part of a message as a quote
=> ✨(front) add button to insert quotes to the draftjs editor

CHANGELOG.md, sandbox/settings.py, src/ashley/defaults.py, src/ashley/machina_extensions/forum_search/search_indexes.py, src/ashley/models.py, src/ashley/templates/forum_search/search.html, tests/ashley/test_forum_search.py
The haystack command `update_index` crashes while indexing posts with
a serialization error. It happens when a message is posted by a user
having an empty public_username field.
This is due to the fact that in this specific case, we are returning a
default public_username ("Anonymous") translated with gettext_lazy.
And lazy proxy values are not directly serializable into JSON.
=> 🐛(search) fix serialization error in search index update

setup.cfg, src/ashley/templates/partials/user_icon.html, tests/ashley/test_templatetags_custom_tags.py
Testing the render of html for the reliability of the project
is essential. Writing these tests in the most simpliest way
is a key point on expanding and maintaining them. We use an
helper dependencie django-with-asserts to help us on redacting
them.
Adding the dependencie django-with-asserts and rewrite the test that target specific element in html
=> 🎨(test) implement simple html content tests

CHANGELOG.md, sandbox/dev_tools/urls.py
Django 3.1 version have introduced deprecated method
RemovedInDjango40Warning: django.conf.urls.url() is deprecated in favor
of django.urls.re_path()
Update the code to follow new recommendations and replace  django.conf.urls.url() by django.urls.re_path()
=> 🗑(sandbox) remove deprecated url in favor of re_path

CHANGELOG.md, sandbox/settings.py, src/ashley/__init__.py, src/ashley/auth/backend.py, src/ashley/machina_extensions/forum_permission/handler.py, src/ashley/machina_extensions/forum_permission/middleware.py, src/ashley/views.py, tests/ashley/lti_utils.py, tests/ashley/machina_extensions/forum_permission/test_permission_handler.py, tests/ashley/machina_extensions/forum_permission/test_permission_middleware.py, tests/ashley/test_auth_backend.py, tests/ashley/test_forum_lti_view.py
When a user is connected to Ashley via LTI, he can see and interact
with all forums he has access to, based on its group membership.
It can be confusing for the user, because he comes from a specific LTI
context and he does not expect to see information related to other
LTI contexts.
In addition to that, group membership synchronization is made during
the LTI authentication process. And it only synchronizes groups for the
current LTI context. So, if we let users access to resources related
to other LTI contexts, we cannot guarantee that user permissions are
correct and it can lead to security issues.
=> ✨(back) limit forum listing to the current user LTIContext id

CHANGELOG.md, src/frontend/js/ashley.ts, src/frontend/js/components/AshleyEditor/index.spec.tsx, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/js/draftjs-plugins/code-editor/index.ts, src/frontend/js/types/libs/draft-js-code/draft-js-code.d.ts, src/frontend/js/utils/highlight.ts, src/frontend/js/utils/test/factories.ts, src/frontend/package.json, src/frontend/scss/_main.scss, src/frontend/scss/objects/_editor.scss, src/frontend/yarn.lock
The input field to add a message is based on the draftjs editor. We want to be able to add a code blocks via this editor.
Syntax highlighting as on github would be nice to have.
https://github.com/openfun/ashley/issues/68
- Add a "code block" button to the editor's toolbar that allows formatting part of a message as code
- Auto-highlighting code displayed in the forum using a lib highlight.js that auto-detects the type of code and provides css.
=> ✨(front) add code blocks to the draftjs editor

CHANGELOG.md, src/ashley/models.py, tests/ashley/test_models_lticontext.py
Currently with the method sync_user_group we can add groups to the user even if this one is not part of the lticontext. This shouldn't be allowed. 
We control that user is part of the lticontext before adding groups.
=> (models) enforce integrity between User and LTIContext

CHANGELOG.md, setup.cfg, src/frontend/package.json
- upgrade django-machina from 1.1.3 to 1.1.4
- add button to insert quotes in the draftjs editor
- limit forum listing to the current user LTIContext id
- add code blocks in the editor and auto-highlight code in the forum
- create a forum for each LTIContext id
- add index to the Forum model
- fix serialization error in search index update
- remove deprecated url in favor of re_path
- prevent inactive users from authenticating via LTI
- prevent linking a User to a LTIContext related to different LTI Consumer
- add frontend test for draft-js editor
- add a ribbon icon when an instructor is the writer of a post or a topic
- add feature in AshleyEditor to mention any active user in the current topic
=> 🔖(ashley) bump version to 1.0.0-beta.5

.circleci/config.yml, .dockerignore, CHANGELOG.md, Dockerfile, src/ashley/templates/board_base.html, src/frontend/webpack.config.js
Webpack uses hashes to name files it generates. But currently, old files stay in place. So after several builds, we can have a js folder with a very large amount of files which is not efficient and furthermore can produce issues and slow down script executions.
In order to clean these files before each build, we need to put them in a dedicated directory to not remove
other js scripts placed in `static/js` directory.
To optimize the build of docker, we ignore `assets` files.
=> 🚚(frontend) clean built frontend files before each build

setup.cfg, tests/ashley/test_templatetags_custom_tags.py
To test html content in backend tests, we've used a deprecated library that
hasn't been updated since 2013. We've replaced it by using directly lxml and
cssselect to clarify the code.
remove django-with-asserts and adding lxml and cssselect and rewrite tests with these two libs directly
=> 🗑️(test) remove lib to test simple html content

.circleci/config.yml, CHANGELOG.md, Dockerfile, src/frontend/package.json, src/frontend/yarn.lock
Docker-compose uses the last node version : node 14. Circle and docker config
files are using the version 10 of node. Node 10 has no compatibility anymore
with some packages. To keep the project updated and to have all the versions
homogenized, an upgrade of node version to version 14 is needed in config files.
Update node version to node 14 and update node dependency when needed
=> 🔧(front) upgrade node version

CHANGELOG.md, src/ashley/factories.py
The proper way to import the user model is by calling get_user_model() method.
To avoid any confusion, we simply fix this import into our factory.
Correct the import by using get_user_model method
=> 🩹(factory) fix import user model

.circleci/config.yml
Node version has been upgraded to version 14 in the previous commit 5196917
For circle task to work properly with node 14, we need to clearly specify
the docker version.
Specifie docker version
=> 🔧(circle) target docker version for hub task

renovate.json
Renovate service is trying to upgrade the version of bootstrap. Ashley is not
configured yet to properly work with version 5 of bootstrap. There is
different breaking styles that need to be fixed first. We still want
renovate to work for other dependencies, so we explicitly exclude
bootstrap from the config of renovate....
Create a packageRule to avoid the upgrade of bootstrap
=> 🔧(renovate) ignore js dependencies bootstrap

renovate.json
Renovate service is trying to update the version of elasticsearch. Ashley can
only work with version 5 of elasticsearch. We create a dedicated package rule
in renovate's config to ignore this specific update.
configure renovate to ignore the update of elasticsearch
=> 🔧(renovate) ignore python dependencies

CHANGELOG.md, src/ashley/machina_extensions/forum/views.py, src/ashley/templates/forum_conversation/topic_list.html, tests/ashley/machina_extensions/forum/test_forum_view.py
There are different kind of topics: regular, sticky and announcements topics.
Sticky topics are supposed to stay on top of the topic listing. Announcements
are displayed in another block that is above the regular topics block and has
its own header columns. Previous commit 3f92f4a enabled sorting topics on
different header columns. This new feature introduces two different
inconstancies. First, sticky topics were sorted as well whereas they are meant
to stay on top of the listing. Second, columns of announcements block when the
order was requested in URL showed toggling arrow as if they were sorted as well.
We only want to sort regular topic discussions and not announcements.
Announcements must stay with the default order which is ordered on the creation
date. The commit introduces these …
=> 🩹(forum) fix sorting on sticky and announcements topics

CHANGELOG.md, src/ashley/machina_extensions/forum_search/forms.py, src/ashley/machina_extensions/forum_search/views.py, tests/ashley/test_forum_search.py
A user can be part of multiple forums attached to different classes.
We want the search to keep is current scope and only search in forums
that are related to the course user is actually logged in. Currently,
a user can search in all the forums he has access to and it can be a
bit confusing. Clicking on a result that lead to another course,
connects the user in a different forum from is original search. Results
might not be even relevant as context is different than expected. To be
more relevant and not to loose our users, we filter results to current
LTIContext and only show results from forum of the current class.
Add a filter to only search on forums from this LTIContext to restrict search
=> 🗑️(back) filter search on current lti_context

CHANGELOG.md, sandbox/dev_tools/forms.py, sandbox/dev_tools/views.py
The sandbox enables to run Ashley in an `iframe`. So far a unique lunch url was set
and its value was defined according to the course id. This was blocking the option
of having multiple forums for the same course using the sandbox. As we are adding
constraints on seeing forums from the same LTIContext, this limit is stopping us from
reproducing cases that we are trying to implement. Adding a lunch URL that can be set
with different values will fix this limit.
Add a field to set up a different lunch URL.
=> 🔧(sandbox) allowing multiple forums for a same LTIContext on sandbox

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Clean built frontend files before each build
- Upgrade node to version 14, the current LTS
- Fix import of the user model in the factory
- Filter search results to current LTIContext
- add react components to manage moderators for current LTIContext
- add django rest framework to promote/revoke moderators for current LTIContext
- add new role moderator and permission to manage moderators
- allow sorting discussion topics
- add a `LTI ID` field in the sandbox settings to be able to have multiple
forums for a same LTIContext
- autoload for AshleyEditor component and translation to frontend
- add API endpoint and Amazon S3 to upload image
- fix sorting on sticky and announcements topics
=> 🔖(ashley) bump version to 1.0.0-beta.6

CHANGELOG.md, src/ashley/machina_extensions/forum_permission/handler.py, tests/ashley/machina_extensions/forum_permission/test_permission_handler.py
When a user displays the list of its unread topics, the list contains
topics belonging to every forums the user has access to. They should
be limited to forums related to the LTIContext the user is coming
from.
=> 🐛(back) limit the scope of the unread topics view

CHANGELOG.md, src/ashley/admin.py
We want to be able to search users by username in django admin. In its
current state, the User admin view is unusable with thousands of
users.
=> ✨(admin) allow to search users by username in django admin

CHANGELOG.md, sandbox/settings.py, setup.cfg, src/ashley/apps.py, src/ashley/receivers.py, src/ashley/xapi.py, tests/ashley/test_receivers.py, tests/ashley/test_xapi.py
We want to track our users' actions using the XAPI standard and
collect these events for analysis.
=> ✨(xapi) track topic views with XAPI events

CHANGELOG.md, src/ashley/machina_extensions/forum_permission/handler.py, src/ashley/machina_extensions/forum_search/forms.py, tests/ashley/machina_extensions/forum_moderation/test_forum_moderation.py, tests/ashley/test_forum_search.py
If a forum gets archived, we shouldn't be able to move topics to
this forum. Lists must ignore archived forums. In the same way, if
we want to use the advanced search, we shouldn't be able to search
in a forum that has been archived.
Exclude archived forums from the two listing
=> 🐛(back) exclude archived forums from select forms

CHANGELOG.md, src/ashley/views.py, tests/ashley/test_forum_lti_view.py
When duplicating courses from an LMS, forums get copied. By default,
each forum has a name set with the value of the course's name. It's
more likely, when a course gets copied, that instructors want to keep
the same forum's names. To simplify this use case, we define the
default name of each forum with an existing UUID to the previous name
defined for the other `context.id`.
When creating a forum, we search if this lti_id already exists to reuse the name.
=> ✨(forum) use the name of a previous forum with the same `lti_id`

CHANGELOG.md, sandbox/dev_tools/forms.py, src/ashley/templates/partials/user_icon.html, src/ashley/templatetags/custom_tags.py, tests/ashley/test_templatetags_custom_tags.py
In previous commit d24b227, an icon has been added to identify
instructors. It will be good to have a logo identifying
administrators as well. Inspired by previous commit d24b227,
we add a ribbon next to their username on topics and posts.
Identify if users are administrators to add a ribbon
=> ✨(front) add an icon for administrator on topic and post

CHANGELOG.md, src/ashley/templates/forum_search/pagination.html, tests/ashley/test_forum_search.py
If results were over three pages, <li> tag was missing its closing
tag resulting in a problem of navigation. Some pages were not
accessible anymore.
Resolve https://github.com/openfun/ashley/issues/240
Fix pagination problem
=> 💄(front) pagination search results

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- use the name of a previous forum with the same `lti_id`
- allow sorting forums on the home page
- add a ribbon icon when an administrator is the writer of a post or a topic
Fixed
- automatically assign a public_username to instructors and administrators
when none is defined for a user already existing
- fix pagination for search results
New release
=> 🔖(ashley) bump version to 1.1.2

CHANGELOG.md, src/ashley/machina_extensions/forum_permission/handler.py, src/ashley/machina_extensions/forum_search/forms.py, tests/ashley/machina_extensions/forum_permission/test_permission_handler.py
If a user was part of multiple courses, search queries were
taking a lot of processing time. DjangoMachina checks the
permissions of the user for each forum he has access to. We only
need to control that the user has the permission to read the forums
part of the current LTIContext. By limiting this query, we fix
at the same time, the problem of the processing time.
With this new method overridden from DjangoMachina, we exclude as
well archived forums.
limit queries with lti_context and archived forums
=> 🐛(back) search queries restricted on LTIContext

CHANGELOG.md, src/ashley/templates/forum_search/search.html, tests/ashley/test_forum_search.py
A topic can have multiple posts and a lot of pages. Search results were targeting the topic on page 1 for any match.
If the post matching the search was on page 10, it made it hard to relate the search and the post. In this condition,
the results didn't seem accurate. To be more precise, we now build a link that directly targets the post on the right
page in the topic.
- build a direct link targeting the post
=> ✨(forum) search links target directly the refered post

.circleci/config.yml
The current ashley version is mentioned in several places in the code: backend, frontend, changelog... All these versions should always be kept in sync. It is not rare to forget to bump a version number when making a release and it can be annoying.
Add a check in CircleCI to make sure all versions are in sync before publishing packages to registries (backend, frontend and changelog).
=> 👷(checks) add check in CI to ensure all versions are in sync

CHANGELOG.md, UPGRADE.md, src/ashley/defaults.py, src/ashley/machina_extensions/forum/urls.py, src/ashley/machina_extensions/forum/views.py, src/ashley/machina_extensions/forum_permission/defaults.py, src/ashley/machina_extensions/forum_permission/handler.py, src/ashley/templates/forum/forum_detail.html, src/ashley/templates/forum/forum_unlock.html, src/ashley/views.py, tests/ashley/test_course_locked.py, tests/ashley/test_course_unlocked.py
A recent feature enabled administrators to lock the forums of a course. Use cases have shown that sometimes, the forums of the course need to be unlocked. This is the case, for instance, when a course is duplicated, the forums get copied but they keep the lock as well. It will now be possible to unlock forums once they have been locked.
- add new permission and enable to lock or unlock forums
=> ✨(forum) unlock all forums of an entire course

CHANGELOG.md, src/ashley/machina_extensions/forum/admin.py, tests/ashley/test_admin.py
The URL of a forum is built using its lti_id. 
Displaying the field lti_id of a forum enables an administrator to have 
access to this useful information.
- override admin django machina to add the field lti_id
=> ✨(admin) display lti_id of a forum

Dockerfile, src/frontend/package.json
Katex npm package is using fonts. These files need to be uploaded into the static folder of django.
Copy fonts in the static folder
=> 🐛(front) fonts for katex lib
