openfun/ashley

CHANGELOG.md, env.d/development/common, sandbox/settings.py, sandbox/urls.py
Install `django-machina` forum in the `sandbox` project without any customization.
=> ✨(sandbox) add base django-machina

Makefile
`ashley` should have the same basic set of Makefile rules than our other projects like `richie` or `marsha`.
Add the following missing rules to the Makefile :
=> 🐳(project) add docker related rules in the Makefile

CHANGELOG.md, sandbox/settings.py, src/ashley/__init__.py, src/ashley/models.py, src/ashley/templates/base.html, src/ashley/templates/board_base.html, src/ashley/templates/forum/forum_list.html, src/ashley/templates/forum/index.html, src/ashley/templates/forum_conversation/partials/topic_detail_actions.html, src/ashley/templates/forum_conversation/topic_list.html, src/ashley/templates/partials/breadcrumb.html
Override some djange-machina's templates, in order to remove some
features to have a basic version of the forum.
=> ✨(ashley) customize django-machina's templates

.gitignore, CHANGELOG.md, Dockerfile, Makefile, crowdin/config.yml, docker-compose.yml, env.d/development/crowdin.dist, sandbox/settings.py, src/ashley/auth/handlers.py, src/ashley/locale/fr_FR/LC_MESSAGES/django.po
Ashley should be able to support multiple languages.
=> ✨(i18n) add i18n support

src/ashley/templates/forum/forum_detail.html
Add missing customized template.
=> 💄(ashley) customize forum index

Makefile, src/ashley/locale/fr_FR/LC_MESSAGES/django.po
=> Typo and translations

Makefile, src/ashley/locale/fr_FR/LC_MESSAGES/django.po
I would like to override some translations made in django-machina.
Generate the .pot file containing messages to translate by merging machina's messages + ashley messages.
=> 🌐(i18n) merge machina translations with ashley

sandbox/settings.py, setup.cfg
We would like to monitor ashley from a loadbalancer and with k8s liveness probe.
Ashley's sandbox should provide healthcheck routes.
=> ➕(sandbox) add and configure dockerflow

.gitignore, CHANGELOG.md, Dockerfile, docker-compose.yml, sandbox/settings.py, src/ashley/static/css/ashley.css, src/ashley/templates/board_base.html
=> Static/media directory configuration and basic stylesheet 

MANIFEST.in
Templates and translations defined in `ashley` application are missing in the `MANIFEST.in` file.
Fix the `MANIFEST.in` file.
=> 🐛(project) add missing files in MANIFEST.in

LICENSE
The LICENSE file is incorrect and refers to "France Université Numérique" instead of "GIP FUN MOOC". Furthermore, the copyright should be _2020-present_ instead of _2020_.
Update the copyright in the LICENSE file.
=> 📄(license) update license

Dockerfile
Remove outdated comment in the Dockerfile :heart:
=> 🔧(project) clean Dockerfile

.circleci/config.yml, CHANGELOG.md, Dockerfile, Makefile, src/ashley/templates/board_base.html, src/frontend/package.json, src/frontend/scss/_main.scss, src/frontend/scss/_variables.scss, src/frontend/scss/objects/_conversation_post_edit.scss, src/frontend/scss/objects/_conversation_topic_detail.scss, src/frontend/scss/objects/_editor.scss, src/frontend/scss/objects/_forum_detail.scss, src/frontend/scss/objects/_forum_lists.scss, src/frontend/scss/objects/_member_profile.scss, src/frontend/scss/objects/_moderation.scss, src/frontend/scss/objects/_search.scss, src/frontend/yarn.lock
Ashley is using CSS files distributed with django-machina.
It does not allow to reuse SASS variables.
=> 🎨(front) reorganize CSS files

CHANGELOG.md, src/ashley/editor/widgets.py, src/frontend/js/components/AshleyEditor/index.tsx, src/frontend/scss/objects/_editor.scss
As a Ashley user, I want to insert links in my forum posts.
Add a button in `AshleyEditor`'s toolbar, using [draft-js-anchor-plugin](https://www.draft-js-plugins.com/plugin/anchor).
=> ✨(front) add button to insert a link in AshleyEditor component

CHANGELOG.md, src/frontend/scss/_variables.scss, src/frontend/scss/objects/_conversation_post_edit.scss, src/frontend/scss/objects/_conversation_topic_detail.scss, src/frontend/scss/objects/_forum_detail.scss, src/frontend/scss/objects/_forum_lists.scss, src/frontend/scss/objects/_member_profile.scss, src/frontend/scss/objects/_moderation.scss
The SASS color variables defined in django-machina theme is not homogeneous with colors defined in bootstrap.
=> 💄(front) coalesce SASS color variables between machina and bootstrap

CHANGELOG.md, src/frontend/scss/_variables.scss
We want Ashley to match fun-mooc's color palette.
(For the moment, without multi-theme support)
=> 💄(front) change SASS colors

README.md
We want to help newcomers get started on the project
We added a quickstart to the README to help with the installation of the project
Closes https://github.com/openfun/ashley/issues/62
=> 🔥(project) add quickstart instructions to readme

Makefile, bin/superuser
To propose an easy way to create an user for the Django admin
Add an entry point in the makefile so that we can use the command 
> make superuser
=> ✨(makefile) create a superuser task

CHANGELOG.md, src/ashley/defaults.py, src/ashley/models.py, src/ashley/templates/forum/forum_list.html, src/ashley/templates/forum_conversation/post_create.html, src/ashley/templates/forum_conversation/topic_detail.html, src/ashley/templates/forum_conversation/topic_list.html, src/ashley/templates/partials/user_icon.html, src/ashley/templatetags/custom_tags.py, src/frontend/scss/_main.scss, src/frontend/scss/objects/_user_badge.scss, tests/ashley/test_models_lticontext.py, tests/ashley/test_templatetags_custom_tags.py
We want to identify when a topic or a post has been created by an instructor
We add an icon next to the username of an instructor when it's the case.
=> ✨(front) add an icon for instructor on topic and post

.circleci/config.yml, Makefile
In our developpement environnement we have an error on the make lint command.
mypyp is actually checking the folder frontend and generating useless error in our make lint command.
We configure it so that it checks only the right files.
=> 🚨(linter) fix mypy target directory

renovate.json
Renovate configuration has changed and some keys have been renamed. It
needs to be updated.
Update renovate config using fun common config
=> 🔧(renovate) update renovate configuration

.gitignore, Makefile, bin/state, bin/terraform, docker-compose.yml, env.d/terraform.dist, terraform/.terraform.lock.hcl, terraform/cloudfront.tf, terraform/create_state_bucket/.terraform.lock.hcl, terraform/create_state_bucket/dynamodb.tf, terraform/create_state_bucket/output.tf, terraform/create_state_bucket/provider.tf, terraform/create_state_bucket/s3.tf, terraform/create_state_bucket/state.tf, terraform/create_state_bucket/versions.tf, terraform/output.tf, terraform/provider.tf, terraform/s3.tf, terraform/state.tf.dist, terraform/variables.tf
In a near future, we want to store ashley medias (see #188) and static files on AWS.
We want to use Terraform to setup the required AWS resources for each environment.
=> ✨(terraform) add terraform configuration

CHANGELOG.md, setup.cfg, src/frontend/package.json
- limit the scope of the unread topics view to the current LTIContext
=> 🔖(ashley) bump to version 1.0.0

CHANGELOG.md, setup.cfg, src/frontend/package.json
Fixed
- exclude archived forums from the list of forums to move topics to
- exclude archived forums from the list of forums of advanced search
bump version to 1.1.1
=> 🔖(ashley) bump version to 1.1.1

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- Allow unlocking all forums of a course
- Display lti_id field on the forum admin panel
=> 🔖(ashley) bump version to 1.2.4

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- Add buttons in the toolbar of Ashley to add inline and block latex
- Enabling latex mathematical equations in forums
=> 🔖(ashley) bump version to 1.3.0

CHANGELOG.md, setup.cfg, src/frontend/package.json
Fixed
- Fix converting in HTML atomic blocks for images
new release
=> 🔖(ashley) bump version to 1.3.1

.circleci/config.yml, Dockerfile, Makefile, bin/_config.sh, docker-compose.yml
We want to use postgres 13, we upgrade the docker image use in the docker compose configuration.
=> ⬆️(compose) upgrade to postgres 13
